title: SecurityNotes
lang: es
description: Random things about information security.

remote_theme: rundocs/jekyll-rtd-theme

edit: true
addons_branch: true

addons:
  - github
  - plugins
  - analytics

copyright:
  revision: true

debug:
  compress: true
  dist: false
  shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
